likecoin/likecoin-wordpress

.circleci/config.yml
likecoin/likecoin.php
likecoin/views/metabox.php

💡 Add inline documentation according to lint

---

CONTRIBUTING.md

Fixes https://github.com/likecoin/likecoin-wordpress/issues/2

📝 Add `CONTRIBUTING.md`

---

likecoin/readme.txt

update readme.txt with new #DePub pitch and post to IPFS thru Matters feature.

📝 Update readme.txt with new #DePub pitch

---

likecoin/admin/options.php
likecoin/admin/views/sponsor.php
likecoin/includes/constant/options.php

💄 Add sponsor likecoin page

---

likecoin/admin/views/components.php
likecoin/admin/views/matters.php
likecoin/admin/views/site-options.php

Add an intro to matters and minor change to matters id display

💄 Add matters intro and improve matters id display

---

likecoin/admin/matters.php

🐛 Try to fix title encode issue with rss title filter

🐛 Fix publish action does not save draft to matters

---

likecoin/admin/views/site-options.php

Should fix https://github.com/likecoin/likecoin-wordpress/issues/79

🐛 Fix publish to matters setting would not save properly

---

likecoin/admin/error.php
likecoin/admin/matters.php

Also remove session token if it expires

🚸 Make matters session expired message more user friendly

---

likecoin/admin/editor.php
likecoin/admin/likecoin.php
likecoin/admin/matters.php
likecoin/admin/metabox.php
likecoin/admin/plugin-action.php
likecoin/admin/views/components.php
likecoin/admin/views/matters.php
likecoin/admin/views/metabox.php
likecoin/admin/views/sponsor.php
likecoin/admin/views/user-options.php
likecoin/includes/class-likecoin-matters-api.php

New info in metabox and post list columns

✨ Add publish/ipfs status and api functions 

---

likecoin/admin/views/metabox.php

Try to mimics the WordPress UI without adding custom CSS

💄 Update metabox UI for publish

---

likecoin/admin/view/view.php

version should be set as plugin version

🐛 Fix script enqueue version is not set properly

---

likecoin/admin/error.php
likecoin/admin/likecoin.php
likecoin/admin/metabox.php
likecoin/admin/plugin-action.php
likecoin/admin/view/view.php
likecoin/includes/constant/options.php
likecoin/js/admin-settings/src/pages/PublishSettingPage.js
likecoin/js/admin/likecoin_metabox.js

Fix broken links in admin pages
Fix matters blocking arweave upload button
Add update text to iscn status

🚸 Improve iscn metabox UX by text update

---

likecoin/admin/view/view.php

🐛 Fix wrong matters option name parsing

---

likecoin/js/admin-settings/src/components/CheckBox.js
likecoin/js/admin-settings/src/components/MainSettingTable.js
likecoin/js/admin-settings/src/index.js
likecoin/js/admin-settings/src/pages/MainSettingPage.js
likecoin/js/admin-settings/src/store/site-likerInfo-store.js

- Error should not be shown when site liker id is not enabled
- Default button show option is `none`

🐛 Fix wrong default select and error message in button options

---

likecoin/js/admin-settings/src/components/MainSettingTable.js

No idea why many component has <tr> wrap, need to refactor later

🎨 Fix broken layout due to strange <tr>

---

likecoin/js/sidebar/src/pages/LikeCoinPlugin.js
likecoin/readme.txt

Update store with data from iscn api response

🐛 Fix depub did not use updated post info

---

likecoin/admin/editor.php

Need to have a text body to make wordpress understand column name

🚸 Add post column text to allow filtering in adv setting

---

likecoin/admin/restful.php

Should not escape html char in title used for JSON payload

🐛 Unescape post title for iscn json payload

---

likecoin/public/likecoin-button.php

Make default option as `bottom` to show likerId if its set but no option is defined

💥 Refactor likecoin button showing logic to prefer enable

---

likecoin/admin/restful.php
likecoin/js/admin/likecoin_metabox.js
likecoin/js/sidebar/src/index.js
likecoin/js/sidebar/src/pages/LikeCoinPlugin.js
likecoin/js/sidebar/src/pages/LikeCoinPluginDocumentSettingPanel.js
likecoin/js/sidebar/src/pages/LikeCoinPluginPrePublishPanel.js
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js
likecoin/js/sidebar/src/store/iscn-info-store.js

~Just a dumb update button that always show~
Added modified date comparison for showing update button

✨ Add update button to depub

---

likecoin/js/sidebar/src/pages/LikeCoinPluginDocumentSettingPanel.js
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js

the condition was not cast to boolean thus might shown as 0

🐛 Fix strange 0 shown in ui

---

likecoin/js/admin-settings/src/components/LikecoinInfoTable.js
likecoin/js/admin-settings/src/components/MainSettingTable.js

Not sure why it was a table, but lets fix the table with proper layout for now
`<th><td>` should be directly under `<tr>` for proper table layout in setting page

💄 Fix LikecoinInfoTable break layout in settings

---

likecoin/admin/iscn.php

excerpt_length was missing is assumed to be 0..

🐛 Fix iscn api cannot fetch description

---

likecoin/js/admin/likecoin_metabox.js
likecoin/js/sidebar/src/index.js
likecoin/js/sidebar/src/pages/LikeCoinPlugin.js
likecoin/js/sidebar/src/pages/LikeCoinPluginDocumentSettingPanel.js
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js
likecoin/js/sidebar/src/store/iscn-info-store.js

✨ Add basic NFT minting and display in sidebar

---

likecoin/js/sidebar/src/pages/LikeCoinPlugin.js
likecoin/js/sidebar/src/pages/LikeCoinPluginDocumentSettingPanel.js
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js
likecoin/js/sidebar/src/store/iscn-info-store.js

Update UI after NFT mint
requires https://github.com/likecoin/app-like-co/pull/194

✨ Add nft minting postMessage support for refresh

---

likecoin/admin/view/restful.php
likecoin/js/sidebar/src/components/LicensePicker.js
likecoin/js/sidebar/src/pages/LikeCoinPlugin.js
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js
likecoin/js/sidebar/src/store/iscn-info-store.js

Requires https://github.com/likecoin/likecoin-wordpress/pull/209

✨ Add license field

---

likecoin/js/admin-settings/src/index.css

💄 Use default style for notice

---

likecoin/admin/restful.php
likecoin/admin/view/view.php
likecoin/js/admin-settings/src/App.js
likecoin/js/admin-settings/src/store/site-likerInfo-store.js
likecoin/js/admin-settings/src/store/user-likerInfo-store.js

♻️ Rename button path to liker-id

---

likecoin/admin/restful.php

🐛 Fix unable to save site Liker Id settings

---

likecoin/js/admin-settings/src/components/Header.js
likecoin/js/admin-settings/src/components/LikerIdTable.js
likecoin/js/admin-settings/src/index.css
likecoin/js/admin-settings/src/pages/LikeCoinHelpPage.js

💄 Minor UI updates of admin panel

---

likecoin/admin/post.php
likecoin/includes/likecoin.php
likecoin/public/likecoin-button.php
likecoin/public/likecoin.php

- Add likecoin meta tags in post/pages
- Add og and likecoin meta tags in iscn post html for upload
- Add default style in iscn post html for upload

✨ Add likecoin meta tag

---

likecoin/js/admin-settings/src/index.css
likecoin/js/admin-settings/src/pages/LikeCoinHelpPage.js

💄 Update getting started page

---

likecoin/readme.txt

- rebranding from "LikeCoin WordPress Plugin" to "Web3Press"
- grammar check

Update readme.txt for Web3Press rebranding

---

likecoin/admin/likecoin.php
likecoin/admin/view/view.php
likecoin/js/admin-settings/src/pages/LikeCoinHelpPage.js
likecoin/js/admin-settings/src/pages/SponsorLikecoinPage.js
likecoin/likecoin.php

✨ Add newsletter in getting start, about and welcome notice

---

likecoin/admin/restful.php
likecoin/admin/view/restful.php
likecoin/js/sidebar/src/pages/LikeCoinPluginSideBar.js
likecoin/js/sidebar/src/store/button-info-store.js

  ✨ Add per post widget setting in sidebar
